# Generated by Django 4.1.1 on 2022-09-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modfied_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nom Produit')),
                ('price', models.FloatField(null=True, verbose_name='Prix Produit')),
                ('description', models.TextField(null=True, verbose_name='Description Produit')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image Produit')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
