# Generated by Django 4.1.1 on 2022-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='modfied_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
