# Generated by Django 4.1.1 on 2022-09-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0003_remove_categorie_product'),
        ('produit', '0002_alter_produit_modfied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorie.categorie'),
        ),
    ]
