# Generated by Django 4.1.1 on 2022-09-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_produit_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
