# Generated by Django 4.1.1 on 2022-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_alter_produit_created_at_alter_produit_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Mise Jour'),
        ),
    ]
