# Generated by Django 4.1.1 on 2022-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Nom Contact')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email Contact')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Telephone Contact')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Sujet Message')),
                ('message', models.TextField(null=True, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
