# Generated by Django 4.1.1 on 2022-09-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatched',
            field=models.BooleanField(null=True, verbose_name='Vu?'),
        ),
    ]
