# Generated by Django 4.1.1 on 2022-09-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_whatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='whatched',
        ),
    ]
