# Generated by Django 4.1.1 on 2022-09-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nom Service')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image Service')),
                ('desc', models.TextField(null=True, verbose_name='Description Service')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Creation')),
            ],
        ),
    ]
