# Generated by Django 4.1.1 on 2022-09-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_categorie_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='product',
        ),
    ]
