# Generated by Django 4.1.1 on 2022-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0003_remove_categorie_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
