# Generated by Django 4.1.1 on 2022-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0004_alter_categorie_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
