# Generated by Django 4.1.1 on 2022-09-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0005_alter_categorie_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Création'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Mise Jour'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom Catégorie'),
        ),
    ]
