# Generated by Django 4.1.1 on 2022-09-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0006_alter_categorie_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='modified_at',
            field=models.DateTimeField(null=True, verbose_name='Date Mise Jour'),
        ),
    ]
