# Generated by Django 4.1.1 on 2022-09-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_inventaire_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Creation'),
        ),
        migrations.AlterField(
            model_name='inventaire',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Mise Jour'),
        ),
    ]
