# Generated by Django 4.1.1 on 2022-09-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_inventaire_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantite Produits'),
        ),
    ]
