# Generated by Django 4.1.1 on 2022-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_alter_inventaire_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventaire',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Mise Jour'),
        ),
    ]
