# Generated by Django 4.1.1 on 2022-09-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_created=True, null=True)),
                ('fullName', models.CharField(max_length=250, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20, null=True)),
                ('hour', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(null=True)),
                ('accepted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
