# Generated by Django 4.1.1 on 2022-09-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepted',
            field=models.BooleanField(null=True, verbose_name='Valide'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='adress',
            field=models.CharField(max_length=100, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Vile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Creation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=20, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='fullName',
            field=models.CharField(max_length=250, null=True, verbose_name='Nom Complet'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.CharField(max_length=20, null=True, verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Mise Jour'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='Code Postal'),
        ),
    ]
