# Generated by Django 4.1.1 on 2022-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_accepted_alter_reservation_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Mise Jour'),
        ),
    ]
