# Generated by Django 4.1.1 on 2022-10-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Heure'),
        ),
    ]
