# Generated by Django 4.1.1 on 2022-10-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_rename_user_reservation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
    ]
